### ISSUE TITLE
Internal Server error occurs.

### ISSUE THREAD

**Issue by aha-oretama** [markstory/lint-review#127]
I'm going to use this lint-review with GitHub Enterprise.

I creat AMI by packer and start instance in AWS.
And I set following parameters in `/etc/environment` in AWS EC2 instance.

```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
LINTREVIEW_GUNICORN_BIND="0.0.0.0:5000"
LINTREVIEW_SETTINGS="/home/ubuntu/settings.py"
LINTREVIEW_SERVER_NAME="hostname:5000"
GITHUB_URL="githubURL"
GITHUB_USERNAME="githubUserName"
GITHUB_PASSWORD="githubPassword"
```

Then, I register the repository , and `X-GitHub-Event: ping` event has succeeded.
But I got internal server error with `X-GitHub-Event: pull_request` event.

This following message is stacktrace.
```
INFO 2017-03-28 13:16:00,056 lintreview.web web:48 Received GitHub pull request notification for git://ghe.misosiru.io/hotpepper-gourmet/perolin.web.git 1175, (reopened) from: git://ghe.misosiru.io/hotpepper-gourmet/perolin.web.git
2017-03-28 13:16:00 [1290] [ERROR] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/sync.py", line 125, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/lintreview/web.py", line 57, in start_review
    gh = get_repository(app.config, head_user, head_repo)
  File "/usr/local/lib/python2.7/dist-packages/lintreview/github.py", line 26, in get_repository
    return gh.repository(owner=user, repository=repo)
AttributeError: 'NoneType' object has no attribute 'repository'
ERROR 2017-03-28 13:16:00,056 gunicorn.error glogging:260 Error handling request
```

Please tell me why internal server error occur and show me the appropriate settings.

**Comment by markstory** [comment]
Looks like your bot user can't clone the repository. Make sure the bot user has the ability to clone the repository. I would recommend using an oauth token over username and password as well.

**Comment by aha-oretama** [comment]
I'll check that the bot user has the ability to clone the repository!!
But I thought that the process of cloning is in [web.py#L68](https://github.com/markstory/lint-review/blob/master/lintreview/web.py#L68)( exactly, in [tasks.py#L54](https://github.com/markstory/lint-review/blob/master/lintreview/tasks.py#L54)).
Therefore, I thought that there is no process of cloning before error occurs.

Is the process of cloning also in [github.py#L25](https://github.com/markstory/lint-review/blob/master/lintreview/github.py#L25)?
Can you tell me where the proces of cloning?

>  I would recommend using an oauth token over username and password as well.

Thank you. I think so too.

**Comment by markstory** [comment]
Cloning happens in tasks.py as you pointed out. However, the webhook handler [does talk to github via the API](https://github.com/markstory/lint-review/blob/master/lintreview/web.py#L59) so if you have a credentials issue there would be problems.

**Comment by aha-oretama** [comment]
I change the bot user which has the ability, and change using oath token.
Then no error occurs!! Thank you @markstory !!

But there is another problem #128.
Please close this question. Thank you for your response.
