### ISSUE TITLE
Suddenly stopped working

### ISSUE THREAD

**Issue by ranvijayj** [markstory/lint-review#185]
getting two errors when I check webhook settings on GitHub

Error code 204:
==> lintreview.access.log <==
"192.30.252.37 - - [28/Feb/2018:11:44:48] "POST /review/start HTTP/1.1" 204 - "-" "GitHub-Hookshot/7a06a51"

And Error code 500

```
INFO 2018-02-28 11:40:33,014 requests.packages.urllib3.connectionpool connectionpool:788 Starting new HTTPS connection (1): api.github.com
2018-02-28 11:40:33 [27774] [ERROR] Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 125, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/lint-review/lintreview/web.py", line 57, in start_review
    gh = get_repository(app.config, head_user, head_repo)
  File "/home/ubuntu/lint-review/lintreview/github.py", line 26, in get_repository
    return gh.repository(owner=user, repository=repo)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/github3/github.py", line 1138, in repository
    json = self._json(self._get(url), 200)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/github3/models.py", line 185, in _get
    return self.session.get(url, **kwargs)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/github3/session.py", line 88, in request
    response = super(GitHubSession, self).request(*args, **kwargs)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/home/ubuntu/lint-review/env/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
    raise SSLError(e, request=request)
SSLError: bad handshake: Error([('SSL routines', 'SSL23_GET_SERVER_HELLO', 'tlsv1 alert protocol version')],)```

**Comment by alzabo** [comment]
I could be wrong, but I just dealt with something similar on some of my Jenkins servers.

GitHub recently updated their public facing web services to require TLS v1.2.

You have an Ubuntu system, but I had to upgrade libnss, libcurl and their depenencies for my CentOS 6 systems. At a guess, you might try running `apt-get upgrade`, but be aware that just running the command without reviewing the changes it will make to your system could have unexpected consequences, break something else, etc.
