### ISSUE TITLE
Linting fails when previous lint job hasn't finished

### ISSUE THREAD

**Issue by alzabo** [markstory/lint-review#202]
I'm noticing an issue that can cause linting to fail for projects where a linter run is in progress for a given PR and more commits are added to the PR.

This happens for me most regularly when using fixers on a copy of a repo with a lot of small files. It looks like the working directory isn't quite empty by the time the next webhook is delivered.

Linting and fixing run OK here:
```
worker_1  | [2018-04-23 18:06:06,361: INFO/Worker-1] JSON was returned
worker_1  | [2018-04-23 18:06:06,362: INFO/Worker-1] Building a url from ('https://ghe.contoso.com/api/v3/repos/alzabo/infrastructure-puppet/pulls/2', 'commits')
worker_1  | [2018-04-23 18:06:06,363: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-04-23 18:06:06,363: INFO/Worker-1] Running fixers on 4 files
worker_1  | [2018-04-23 18:06:06,364: INFO/Worker-1] Running fixer rubocop on 1 files
worker_1  | [2018-04-23 18:06:06,364: INFO/Worker-1] Running ruby2 container
worker_1  | [2018-04-23 18:06:07,919: INFO/Worker-1] Running fixer puppet-lint on 1 files
worker_1  | [2018-04-23 18:06:07,920: INFO/Worker-1] Running ruby2 container
worker_1  | [2018-04-23 18:06:08,587: INFO/Worker-1] Using commit workflow to apply fixer changes
worker_1  | [2018-04-23 18:06:11,941: INFO/Worker-1] Running lint tools on 4 files
worker_1  | [2018-04-23 18:06:11,942: INFO/Worker-1] Running rubocop on 1 files
worker_1  | [2018-04-23 18:06:11,942: INFO/Worker-1] Running ruby2 container
worker_1  | [2018-04-23 18:06:13,083: INFO/Worker-1] Running puppet-lint on 1 files
worker_1  | [2018-04-23 18:06:13,084: INFO/Worker-1] Running ruby2 container
worker_1  | [2018-04-23 18:06:13,703: INFO/Worker-1] Building a url from ('https://ghe.contoso.com/api/v3/repos/alzabo/infrastructure-puppet/pulls/2', 'comments')
worker_1  | [2018-04-23 18:06:13,704: INFO/Worker-1] Missed the cache building the url
worker_1  | [2018-04-23 18:06:13,777: INFO/MainProcess] Received task: lintreview.tasks.process_pull_request[f4227a74-4cfc-4ed1-9b9b-ed2202434792]
worker_1  | [2018-04-23 18:06:13,780: INFO/Worker-2] Starting to process lint for 
worker_1  | [2018-04-23 18:06:13,781: INFO/Worker-2] Loading pull request data from github. user=alzabo repo=infrastructure-puppet number=2
worker_1  | [2018-04-23 18:06:13,782: INFO/Worker-2] Building a url from ('https://ghe.contoso.com/api/v3', 'repos', 'alzabo', 'infrastructure-puppet')
worker_1  | [2018-04-23 18:06:13,782: INFO/Worker-2] Missed the cache building the url
worker_1  | [2018-04-23 18:06:13,898: INFO/Worker-1] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-04-23 18:06:13,900: INFO/Worker-1] JSON was returned
worker_1  | [2018-04-23 18:06:13,905: INFO/Worker-1] Publishing review of 0 new comments for alzabo/infrastructure-puppet/pull/2
worker_1  | [2018-04-23 18:06:14,199: INFO/Worker-2] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-04-23 18:06:14,200: INFO/Worker-2] JSON was returned
worker_1  | [2018-04-23 18:06:14,204: INFO/Worker-2] Building a url from ('https://ghe.contoso.com/api/v3/repos/alzabo/infrastructure-puppet', 'pulls', '2')
worker_1  | [2018-04-23 18:06:14,204: INFO/Worker-2] Missed the cache building the url
worker_1  | [2018-04-23 18:06:14,226: INFO/Worker-1] Attempting to get JSON information from a Response with status code 201 expecting 201
worker_1  | [2018-04-23 18:06:14,226: INFO/Worker-1] JSON was returned
worker_1  | [2018-04-23 18:06:14,227: INFO/Worker-1] Building a url from ('https://ghe.contoso.com/api/v3/repos/alzabo/infrastructure-puppet', 'statuses', '69e44942da37f5e741661474df3b516246eb0096')
worker_1  | [2018-04-23 18:06:14,359: INFO/Worker-2] Attempting to get JSON information from a Response with status code 200 expecting 200
worker_1  | [2018-04-23 18:06:14,360: INFO/Worker-2] JSON was returned
worker_1  | [2018-04-23 18:06:14,363: INFO/Worker-2] Building a url from ('https://ghe.contoso.com/api/v3/repos/alzabo/infrastructure-puppet', 'statuses', 'dfd8bcdabeadc24aa056cc5d60b6dbcc5b12cedf')
worker_1  | [2018-04-23 18:06:14,364: INFO/Worker-2] Missed the cache building the url
worker_1  | [2018-04-23 18:06:14,367: INFO/Worker-1] Attempting to get JSON information from a Response with status code 201 expecting 201
worker_1  | [2018-04-23 18:06:14,367: INFO/Worker-1] JSON was returned
worker_1  | [2018-04-23 18:06:14,369: INFO/Worker-1] Completed lint processing for alzabo/infrastructure-puppet/2
alzabo/infrastructure-puppet/2
```

The next webhook starts to be evaluated here:
```
worker_1  | [2018-04-23 18:06:14,483: INFO/Worker-2] Attempting to get JSON information from a Response with status code 201 expecting 201
worker_1  | [2018-04-23 18:06:14,484: INFO/Worker-2] JSON was returned
```

Cloning fails:
```
worker_1  | [2018-04-23 18:06:14,485: INFO/Worker-2] Cloning repository 'https://ghe.contoso.com/alzabo/infrastructure-puppet.git' into '/tmp/workspace/alzabo/infrastructure-puppet/2'
worker_1  | [2018-04-23 18:06:14,494: ERROR/Worker-2] STDERR output: fatal: destination path '/tmp/workspace/alzabo/infrastructure-puppet/2' already exists and is not an empty directory.
worker_1  |
worker_1  | [2018-04-23 18:06:14,495: ERROR/Worker-2] Unable to clone repository into '/tmp/workspace/alzabo/infrastructure-puppet/2'
worker_1  | [2018-04-23 18:06:14,495: ERROR/Worker-2] Unable to clone repository into '/tmp/workspace/alzabo/infrastructure-puppet/2'
worker_1  | Traceback (most recent call last):
worker_1  |   File "/code/lintreview/tasks.py", line 51, in process_pull_request
worker_1  |     git.clone_or_update(config, clone_url, target_path, pr_head)
worker_1  |   File "/code/lintreview/git.py", line 76, in clone_or_update
worker_1  |     authenticated_clone(config, url, path)
worker_1  |   File "/code/lintreview/git.py", line 45, in authenticated_clone
worker_1  |     clone(url, path)
worker_1  |   File "/code/lintreview/git.py", line 17, in wrapper
worker_1  |     return func(*args, **kwargs)
worker_1  |   File "/code/lintreview/git.py", line 55, in clone
worker_1  |     raise IOError(u"Unable to clone repository into '{}'".format(path))
worker_1  | IOError: Unable to clone repository into '/tmp/workspace/alzabo/infrastructure-puppet/2'
worker_1  | [2018-04-23 18:06:14,502: INFO/MainProcess] Task lintreview.tasks.process_pull_request[f4227a74-4cfc-4ed1-9b9b-ed2202434792] succeeded in 0.722406757995s: None
```

The workspace is cleaned up:
```
worker_1  | [2018-04-23 18:06:14,862: INFO/Worker-1] Cleaned up pull request alzabo/infrastructure-puppet/2
worker_1  | [2018-04-23 18:06:14,866: INFO/MainProcess] Task lintreview.tasks.process_pull_request[4a1e30c7-3cb7-4a62-a024-75a4cec11551] succeeded in 33.171103843s: None
[root@lint-review2 lint-review]# ls -la /tmp/workspace/alzabo/infrastructure-puppet/2
ls: cannot access /tmp/workspace/alzabo/infrastructure-puppet/2: No such file or directory
[root@lint-review2 lint-review]# ls -la /tmp/workspace/alzabo/infrastructure-puppet/
total 8
drwxr-xr-x 2 root root 4096 Apr 23 18:06 .
drwxr-xr-x 3 root root 4096 Apr 23 18:05 ..
[root@lint-review2 lint-review]#
```

**Comment by markstory** [comment]
You should run fewer workers processes in celery. By default celery will run as many processes as you have processors/cores. You might want to dial that back.

**Comment by alzabo** [comment]
Updating the celery options in my docker-compose file to add `--concurrency 1` looks to have fixed the problem for the repo I had that always failed. Thanks!
